# Generated by Django 4.2.4 on 2023-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_photo',
            field=models.ImageField(default='default/bear.png', upload_to='receptionist/patients/'),
        ),
    ]
