# Generated by Django 4.2.4 on 2023-08-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
