# Generated by Django 4.2.4 on 2023-09-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_remove_patient_user_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='unknown@email.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
